### ISSUE TITLE
Error installing plugin

### ISSUE THREAD

**Issue by BASICjfisher** [la-haute-societe/craft-google-tag-manager#1]
I am running into an error installing this plugin via composer and via the admin:

Error: Couldn't install la-haute-societe/craft-google-tag-manager: Unable to determine the base path

```
Composer output: Cannot create cache directory /usr/share/httpd/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /usr/share/httpd/.composer/cache/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /usr/share/httpd/.composer/cache/repo/https---composer.craftcms.com/, or directory is not writable. Proceeding without cache
Cannot create cache directory /usr/share/httpd/.composer/cache/files/, or directory is not writable. Proceeding without cache
Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Package operations: 1 install, 0 updates, 0 removals
- Installing la-haute-societe/craft-google-tag-manager (1.0.0): Downloading (connecting...)Downloading (100%)
- Removing la-haute-societe/craft-google-tag-manager (1.0.0)
```

[This repo](https://github.com/fruitstudios/craft-linkit/issues/15) references a similar issue where the casing of the name of the plugin, but I don't know if that is of any help here.

**Comment by juban** [comment]
Hi,

Thank you for the report. 
Not sure your issue is related to the one you mentioned. 
We’re going to investigate and let you know. 

Regards.

**Comment by juban** [comment]
Turns out you’re right and this is related. 
We have a file naming issue. 
We will push a fix very soon. 
Sorry for the inconvenience.

**Comment by juban** [comment]
Version 1.0.1 should fix the issue.
Please, let us know if it's OK for you. Thanks.

**Comment by BASICjfisher** [comment]
This looks like it worked. I was able to install via the plugin store in the control panel. Thank you for the quick response!
