### ISSUE TITLE
Craft 4

### ISSUE THREAD

**Issue by ryssbowh** [la-haute-societe/craft-google-tag-manager#3]
Hi,

Is a Craft 4 version to be expected for this plugin ?

Thank you

**Comment by nstcactus** [comment]
Hi,

Sorry for having never replied to you…
[Version 2.0.0](https://github.com/la-haute-societe/craft-google-tag-manager/blob/master/CHANGELOG.md#200---2022-08-24) has been released last year which brings Craft 4 compatibility.
