### ISSUE TITLE
delete me

### ISSUE THREAD

**Issue by baronvertigovongrahamthesecondofsealand** [la-haute-societe/craft-google-tag-manager#4]

**Comment by nstcactus** [comment]
At the moment it doesn't as you would expect it, by simply entering the environment variable name in the desired field of the plugin settings page.

What you can do to work around this issue is to use the config file like so:

````php
<?php 

// craft/config/google-tag-manager.php

use \craft\helpers\App;

return [
    'containerID' => App::env('GTM_CONTAINER_ID'),
];
````
