### ISSUE TITLE
Craft 5 compatability

### ISSUE THREAD

**Issue by JordanMed** [la-haute-societe/craft-google-tag-manager#5]
I see there haven't been any changes to this repo since 2022. Just wondering if this is an abandoned plugin or not? A craft 5 version would be welcome.

**Comment by likeabas** [comment]
@nstCactus I've created a pull request for Craft 5 support, would you mind have a look and merge?
https://github.com/la-haute-societe/craft-google-tag-manager/pull/6

**Comment by GeoFeij** [comment]
@mathieu-coingt, would it be possible to create a new release with the craft 5 compatibility please? Thanks in advance!
